modLoader = "javafml" #mandatory
loaderVersion = "[39,)" #mandatory
issueTrackerURL = "https://github.com/Lomeli12/TrophySlots/issues" #optional
license = "LGPLv3"

[[mods]]
modId = "trophyslots"
version = "${file.jarVersion}"
displayName = "Trophy Slots"
updateJSONURL = "https://raw.githubusercontent.com/Lomeli12/TrophySlots/1.18/forge-update.json"
displayURL = "http://lomeli12.net/"
logoFile = "logo.png"
credits = "Lomeli"
authors = "Lomeli"
description = '''
Locks slots in your inventory until you earn them back.
'''

[[dependencies.trophyslots]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trophyslots]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"
